# Generated by Django 2.2.5 on 2019-09-12 11:07

from django.db import migrations
import verify_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', verify_app.models.UserManager()),
            ],
        ),
    ]
