# Generated by Django 2.2.5 on 2019-09-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0002_auto_20190912_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(unique=True),
        ),
    ]
